### ISSUE TITLE
Info request

### ISSUE THREAD

**Issue by benjamin-pinaya-tierconnect-com** [mack2402/NASA2015-app-challenge-Project-Chronos#1]
Build instructions? .exe or something we can see? The diagrams alone don't help.

**Comment by vucket** [comment]
You can download the game. exe from here
https://www.dropbox.com/s/u5kyn6h7fc94qvm/Build%20Con%20Oculus.rar?dl=0

Of course it is a build that works without Oculus Rift & Hardware

Enjoy :)
